#!/bin/bash
set -e

cd $(dirname $0)/..

echo "Start building ISO image"

HARVESTER_INSTALLER_VERSION=iso-upgrade

git clone --branch ${HARVESTER_INSTALLER_VERSION} --single-branch --depth 1 https://github.com/gitlawr/harvester-installer.git ../harvester-installer

cd ../harvester-installer/scripts

#test
export HARVESTER_INSTALLER_OFFLINE_BUILD=1

./ci

mkdir -p ../../harvester/dist/artifacts
cp ../dist/artifacts/* ../../harvester/dist/artifacts

