#!/bin/bash
set -e

cd $(dirname $0)/..

echo "Start building ISO image"

HARVESTER_INSTALLER_VERSION=master

git clone --branch ${HARVESTER_INSTALLER_VERSION} --single-branch --depth 1 https://github.com/rancher/harvester-installer.git ../harvester-installer

cd ../harvester-installer/scripts

./ci

for file in `find ../dist/artifacts -type f -name 'k3os*'`; do mv "$file" "../${file/k3os/harvester}"; done

