#!/bin/bash
set -e

cd $(dirname $0)/..

echo "Start building ISO image"

HARVESTER_INSTALLER_VERSION=v0.1.3

git clone --branch ${HARVESTER_INSTALLER_VERSION} --single-branch --depth 1 https://github.com/rancher/harvester-installer.git ../harvester-installer

cd ../harvester-installer/scripts

./ci

cd $(dirname $0)/..
HARVESTER_DIR=../harvester
cp -r manifests ${HARVESTER_DIR}/package
cp k3os/images/70-iso/charts/harvester-*.tgz ${HARVESTER_DIR}/package
mkdir -p ${HARVESTER_DIR}/dist/artifacts
cp dist/artifacts/* ${HARVESTER_DIR}/dist/artifacts

